compras/urls.py
from django.urls import path
from .views import TelaCompra, FinalizaCompra, RemoverProduto, LimpaCarrinho, MostraTotalGasto

urlpatterns = [
    path('realizar_compras/', TelaCompra, name='realizar_compras'),
    path('finaliza_compra/', FinalizaCompra, name="finaliza_compra"),
    path('remover_produto/<int:index>', RemoverProduto, name="remover_produto"),
    path('limpar_carrinho/', LimpaCarrinho, name="limpar_carrinho"),
    path('mostra_gasto/', MostraTotalGasto, name="mostra_gasto"),
]

projeto_conveniencia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('colaboradores/', include('colaboradores.urls')),
    path('produtos/', include('produtos.urls')),
    path('compras/', include('compras.urls')),
    path('relatorios/', include('relatorios.urls')),
    path('estoque/', include('estoque.urls')),
    path('reports/', include('reports.urls')),
]

relatorios/urls.py
from django.urls import path
from .views import GerarRelatorios, RelatorioColab, RelatorioProduto, GerarRelatorioCompras

urlpatterns =[
    path('gerar_relatorios/', GerarRelatorios, name='gerar_relatorios'),
    path('relatorio_colab/', RelatorioColab, name='relatorio_colab'),
    path('relatorio_produto/', RelatorioProduto, name='relatorio_produto'),
    path('relatorio_compras/', GerarRelatorioCompras, name='relatorio_compras'),

]

compras/models.py
from django.db import models
from colaboradores.models import Colaborador
from produtos.models import Produto

class RegistroCompra(models.Model):
    colab_id = models.ForeignKey(Colaborador, on_delete=models.PROTECT)
    produtos = models.ManyToManyField(Produto, through='ItemCompra')
    data_compra = models.DateTimeField()

    def __str__(self):
        return self.colab_id.nome
    
class ItemCompra(models.Model):
    compra = models.ForeignKey(RegistroCompra, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    quantidade = models.IntegerField()
    preco_individual = models.FloatField()

    def __str__(self):
        return self.produto.nome

relatorios/views.py
from django.shortcuts import render, redirect
from colaboradores.models import Colaborador
from produtos.models import Produto
from compras.models import RegistroCompra, ItemCompra
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from datetime import datetime, date, timedelta
from django.contrib import messages

import locale


def GerarRelatorios(request):

    produtos = Produto.objects.all()
    colabs = Colaborador.objects.all()

    context = {
        'colabs' : colabs,
        'produtos' : produtos
    }
    return render(request, "gerar_relatorios.html", context)
    
def RelatorioColab(request):
    locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
    if request.method == 'POST':
        colab_id = request.POST.get('colaborador')
        data_inicial = request.POST.get('data_inicial')
        data_final = request.POST.get('data_final')
        
        funcionario = Colaborador.objects.get(id=colab_id)
        compras = RegistroCompra.objects.filter(colab_id=funcionario)

        add_dia = timedelta(days=1)

        if data_inicial and data_final:
            data_inicial = datetime.strptime(data_inicial, '%Y-%m-%d')
            data_final = datetime.strptime(data_final, '%Y-%m-%d')

            if(data_inicial > data_final):
                messages.error(request, 'Data inválida')
                return redirect('gerar_relatorios')

            compras = compras.filter(data_compra__range=(data_inicial, data_final+add_dia))

        itens = ItemCompra.objects.filter(compra__in=compras)
        venda_total = 0
        for item in itens:
            venda_total += item.quantidade * item.preco_individual

             
        venda_total_formatada = locale.currency(venda_total, grouping=True)

        for produto in itens:
            produto.preco_individual_formatado = locale.currency(produto.preco_individual, grouping=True, symbol=True)


        context = {
            'funcionario': funcionario,
            'compras': compras,
            'itens': itens,
            'venda_total' : venda_total,
            'venda_total_formatada' : venda_total_formatada,
            'data_inicial': data_inicial, 
            'data_final': data_final, 
        }

        template = get_template('template_relatorio.html')
        html = template.render(context)

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="relatorio.pdf"'

        pisa.CreatePDF(html, dest=response)

        return response
    
def RelatorioProduto(request):
    locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

    if request.method == 'POST':
        produto_id = request.POST.get('produto')
        data_inicial = request.POST.get('data_inicial')
        data_final = request.POST.get('data_final')
        print(produto_id)
        produto = Produto.objects.get(id=produto_id)
        compras = RegistroCompra.objects.filter(produtos__id=produto_id)

        add_dia = timedelta(days=1)

        if data_inicial and data_final:
            data_inicial = datetime.strptime(data_inicial, '%Y-%m-%d')
            data_final = datetime.strptime(data_final, '%Y-%m-%d')

            if(data_inicial > data_final):
                messages.error(request, 'Data inválida')
                return redirect('gerar_relatorios')

            compras = compras.filter(data_compra__range=(data_inicial, data_final+add_dia))

        itens_compra = ItemCompra.objects.filter(produto__id=produto_id)

        venda_total = 0
        quantidade_vendida = 0
        for item in itens_compra:
            venda_total += item.quantidade * item.preco_individual
            quantidade_vendida += item.quantidade

        venda_total_formatada = locale.currency(venda_total, grouping=True)


        context = {
            'produto': produto,
            'compras': compras,
            'itens_compra': itens_compra,
            'venda_total_formatada': venda_total_formatada,
            'quantidade_vendida' : quantidade_vendida,
            'data_inicial': data_inicial, 
            'data_final': data_final, 
        }

        template = get_template('template_relatorio_produto.html')
        html = template.render(context)

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename=relatorio_produto.pdf'

        pisa.CreatePDF(html, dest=response)

        return response
    

def GerarRelatorioCompras(request):
    locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')

    if request.method == 'POST':
        data_inicial = request.POST.get('data_inicial')
        data_final = request.POST.get('data_final')
        
        try:
            data_inicial = datetime.strptime(data_inicial, '%Y-%m-%d').date()
            data_final = datetime.strptime(data_final, '%Y-%m-%d').date()
            add_dia = timedelta(days=1)
        except:
            return redirect('gerar_relatorios')
        
        if(data_inicial > data_final):
                messages.error(request, 'Data inválida')
                return redirect('gerar_relatorios')
        
        compras = RegistroCompra.objects.filter(data_compra__range=(data_inicial, data_final+add_dia))
        itens = ItemCompra.objects.filter(compra__in=compras)

        venda_total = 0

        for item in itens:
            venda_total += item.quantidade * item.preco_individual

        venda_total_formatada = locale.currency(venda_total, grouping=True, symbol=True)
        

        locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
        for produto in itens:
            produto.preco_individual_formatado = locale.currency(produto.preco_individual, grouping=True, symbol=True)

        context = {
            'compras': compras,
            'itens': itens,
            'data_inicial': data_inicial, 
            'data_final': data_final, 
            'venda_total_formatada' : venda_total_formatada
        }

        data_inicial_str = data_inicial.strftime('%Y-%m-%d')
        data_final_str = data_final.strftime('%Y-%m-%d')

        template = get_template('template_relatorio_compras.html')
        html = template.render(context)

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="relatorio_compras_{data_inicial_str}_{data_final_str}.pdf"'

        pisa.CreatePDF(html, dest=response)

        return response

relatorios/templates/gerar_relatorios.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Gerar Relatórios</title>
    <link rel="icon" href="{% static 'img/logo-sci-site.png'%}" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.0/mdb.min.css" rel="stylesheet" />
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #2d3560;">
        <!-- Container wrapper -->
        <div class="container">
        <!-- Navbar brand -->
        <a class="navbar-brand me-2" href="{% url 'dashboard' %}" >
            <img
            width="150px"
            src="https://www.sci.com.br/arquivo/banner/56/95294737.png"
            alt="MDB Logo"
            loading="lazy"
            style="margin-top: -1px;"
            />
        </a>
    
        <!-- Toggle button -->
        <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbarButtonsExample"
            aria-controls="navbarButtonsExample"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
            <!-- Left links -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    
                </li>
            </ul>
            <!-- Left links -->
    
            <div class="d-flex align-items-center">
            <a href="{% url 'gerar_relatorios' %}" class="px-3 me-2" style="color: white;">
                RELATÓRIOS
            </a>
            <a href="{% url 'mostra_produtos' %}" class="px-3 me-2" style="color: white;">
                PRODUTOS
            </a>
            <a href="{% url 'mostra_estoque' %}" class="px-3 me-2" style="color: white;">
                ESTOQUE
            </a>
            <a href="{% url 'mostra_colabs' %}" class="px-3 me-2" style="color: white;">
                COLABORADORES
            </a>
            {% if user.is_superuser %}
            <a href="{% url 'mostra_usuario' %}" class="px-3 me-2" style="color: white;">
                USUÁRIOS
            </a>
            {% endif %}
            <a href="{% url 'logout' %}" class="btn btn-secondary me-3" style="background-color: white;">
                Logout
            </a>
            </div>
        </div>
        <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->

    <div class="container d-flex justify-content-center align-items-center">
        <div class="row justify-content-center">
            <div class="col justify-content-center">
                {% if messages %}
                    <div class="justify-content-center align-items-center" style="height: 100vh; position: fixed; top: 100px; left: 44.5%;">
                        <div class="alert alert-danger mt-4" role="alert"
                             style="padding: 6px; width: 200px; text-align: center; border-top: 7px solid red;">
                            {% for message in messages %}
                                {% if message.tags == 'success' %}
                                    {{ message }}
                                {% elif message.tags == 'error' %}
                                    {{ message }}
                                {% else %}
                                    <p>{{ message }}</p>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="container" style="margin-top: 200px;">
        <div class="row justify-content-center">
            <div class="col col-sm-4">
                <form action="{% url 'relatorio_colab' %}" method="POST">
                    {% csrf_token %}
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #2d3560; color: white; font-weight: 800;">Relatório Colaboradores</div>
                            <div class="card-body">
                                <div class="container">
                                        <select name="colaborador" class="form-select form-select-md mb-3" style="height: 50px; color: black;" required>
                                            <option value="" selected disabled>Colaborador</option>
                                            {% for colab in colabs %}
                                                <option value="{{colab.id}}" >{{colab.nome}}</option>
                                            {% endfor %}
                                        </select>
                                        <div class="form-outline mb-3">
                                            <input name="data_inicial" type="date" id="di" class="form-control form-control-lg cpf" style="color: rgba(0, 0, 0, 0.637);"/>
                                            <label class="form-label" for="di" style="color: rgb(0, 0, 0);">Data Inicio</label>
                                        </div>
                                        <div class="form-outline mb-3">
                                            <input name="data_final" type="date" id="df" class="form-control form-control-lg" style="color: rgba(0, 0, 0, 0.637);"/>
                                            <label class="form-label" for="df" style="color: rgb(0, 0, 0);">Data Término</label>
                                        </div>
                                </div>
                            </div>
                        <div class="card-footer" style="background-color: rgb(253, 253, 253);">
                            <input type="submit" class="btn btn-primary" style="background-color: #2d3560; box-shadow: none;" value="Gerar Relatório">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col col-sm-4">
                <form action="{% url 'relatorio_compras' %}" method="POST">
                    {% csrf_token %}
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #2d3560; color: white; font-weight: 800;">Relatório Geral</div>
                            <div class="card-body">
                                <div class="container">
                                    <div class="form-outline mb-3">
                                        <input required name="data_inicial" type="date" id="di" class="form-control form-control-lg cpf" style="color: rgba(0, 0, 0, 0.637);"/>
                                        <label class="form-label" for="di" style="color: rgb(0, 0, 0);">Data Inicio</label>
                                    </div>
                                    <div class="form-outline mb-3">
                                        <input required name="data_final" type="date" id="df" class="form-control form-control-lg" style="color: rgba(0, 0, 0, 0.637);"/>
                                        <label class="form-label" for="df" style="color: rgb(0, 0, 0);">Data Término</label>
                                    </div>
                                </div>
                            </div>
                        <div class="card-footer" style="background-color: rgb(253, 253, 253);">
                            <input type="submit" class="btn btn-primary" style="background-color: #2d3560; box-shadow: none;" value="Gerar Relatório">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col col-sm-4">
                <form action="{% url 'relatorio_produto' %}" method="POST">
                    {% csrf_token %}
                    <div class="card text-center">
                        <div class="card-header" style="background-color: #2d3560; color: white; font-weight: 800;">Relatório Produtos</div>
                            <div class="card-body">
                                <div class="container">
                                    <select name="produto" class="form-select form-select-md mb-3" style="height: 50px; color: black;" required>
                                        <option value="null" selected disabled>Produto</option>
                                        {% for produto in produtos %}
                                            <option value="{{produto.id}}">{{produto.nome}}</option>
                                        {% endfor %}
                                    </select>
                                    <div class="form-outline mb-3">
                                        <input required name="data_inicial" type="date" id="di" class="form-control form-control-lg cpf" style="color: rgba(0, 0, 0, 0.637);"/>
                                        <label class="form-label" for="di" style="color: rgb(0, 0, 0);">Data Inicio</label>
                                    </div>
                                    <div class="form-outline mb-3">
                                        <input required name="data_final" type="date" id="df" class="form-control form-control-lg" style="color: rgba(0, 0, 0, 0.637);"/>
                                        <label class="form-label" for="df" style="color: rgb(0, 0, 0);">Data Término</label>
                                    </div>
                                </div>
                            </div>
                        <div class="card-footer" style="background-color: rgb(253, 253, 253);">
                            <input type="submit" class="btn btn-primary" style="background-color: #2d3560; box-shadow: none;" value="Gerar Relatório">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <footer class="text-center text-lg-start bg-white text-muted fixed-bottom" style="border-top: 10px solid rgb(218, 203, 0);">
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: #2d3560; color: white;">
          © 2023 Copyright:
          <a class="text-reset fw-bold">SCI Sistemas Contábeis</a>
        </div>
        <!-- Copyright -->
    </footer>

    <script>
        const successMessage = document.querySelector('.alert');
        const errorMessage = document.querySelector('.alert');

        if (successMessage) {
            const duration = 3000;

            setTimeout(function() {
                successMessage.style.display = 'none';
            }, duration);
        }

        if (errorMessage) {
            const duration = 3000;

            setTimeout(function() {
                errorMessage.style.display = 'none';
            }, duration);
        }
    </script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
      </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
      integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous">
      </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </body>

</html>

relatorios/templates/template_relatorio.html
{% load static %}
<html>
<head>
    <title>Relatório de Compras</title>
    <style>
    </style>
</head>
<body>
    <h1>Relatório de Compras</h1>
    
    <h2> Funcionario: {{funcionario.nome}}</h2>
    <h2>Período: {{ data_inicial|date:"d/m/Y" }} - {{ data_final|date:"d/m/Y" }}</h2>
    <h3>Compras realizadas:</h3>
    <table>
        <thead>
            <tr>
                <th style="text-align: left;">Data e Hora</th>
                <th style="text-align: left;">Produto</th>
                <th style="text-align: left;">Quantidade</th>
                <th style="text-align: right;">Preço Individual</th>
            </tr>
        </thead>
        <tbody>
            {% for compra in compras %}
                {% for item in compra.itemcompra_set.all %}
                    <tr>
                        <td style="text-align: left;">{{ compra.data_compra }}</td>
                        <td style="text-align: left;">{{ item.produto.nome }}</td>
                        <td style="text-align: left;">{{ item.quantidade }}</td>
                        <td style="text-align: right;">{{ item.preco_individual }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
                    <tr>
                        <td style="text-align: left;">Valor total:</td>
                        <td style="text-align: left;"></td>
                        <td style="text-align: left;"></td>
                        <td style="text-align: right;">{{ venda_total_formatada }}</td>
                    </tr>
        </tbody>
        
    </table>
</body>
</html>

relatorios/templates/template_relatorio_compras.html
{% load static %}
<html>
<head>
    <title>Relatório de Compras</title>
    <style>
    </style>
</head>
<body>
    <img width="400px" src="{% static 'img/logo-sci.png'%}">
    <h1>Relatório de Compras</h1>
    <h2>Período: {{ data_inicial|date:"d/m/Y" }} - {{ data_final|date:"d/m/Y" }}</h2>
    <h3>Compras realizadas:</h3>
    <table>
        <thead>
            <tr>
                <th style="text-align: left;">Data e Hora</th>
                <th style="text-align: left;">Colaborador</th>
                <th style="text-align: left;">Produto</th>
                <th style="text-align: left;">Quantidade</th>
                <th style="text-align: right;">Preço Individual</th>
            </tr>
        </thead>
        <tbody>
            {% for compra in compras %}
                {% for item in compra.itemcompra_set.all %}
                    <tr style="margin-bottom: 3px;">
                        <td style="text-align: left;">{{ compra.data_compra }}</td>
                        <td style="text-align: left;">{{ compra.colab_id.nome }}</td>
                        <td style="text-align: left;">{{ item.produto.nome }}</td>
                        <td style="text-align: left;">{{ item.quantidade }}</td>
                        <td style="text-align: right;">R$ {{ item.preco_individual }}0</td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </tbody>
    </table>
    <h2>Total de vendas: {{ venda_total_formatada }}</h2>
</body>
</html>

relatorios/templates/template_relatorio_produto.html
{% load static %}
<html>
<head>
    <title>Relatório de Compras</title>
    <style>
        body {
            flex-direction: column;
        }
        
        table {
            border-collapse: collapse;
        }
        
    </style>
</head>
<body>
    <img width="400px" src="{% static 'img/logo-sci.png'%}">
    <h1>Relatório de Vendas</h1>

    <h2>Produto: {{ produto.nome }}</h2>
    <h2>Período: {{ data_inicial|date:"d/m/Y" }} - {{ data_final|date:"d/m/Y" }}</h2>

    <h3>Vendas:</h3>
    <table>
        <thead>
            <tr>
                <th style="text-align: left;">Data e Hora</th>
                <th style="text-align: left;">Codigo de Barras</th>
                <th style="text-align: left;">Quantidade</th>
                <th style="text-align: right;">Preço Vendido</th>
            </tr>
        </thead>
        <tbody>
            {% for item in itens_compra %}
                <tr>
                    <td style="text-align: left;">{{ item.compra.data_compra }}</td>
                    <td style="text-align: left;">{{ item.produto.codigo_de_barras }}</td>
                    <td style="text-align: left;">{{ item.quantidade }}</td>
                    <td style="text-align: right;">{{ item.preco_individual }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2>Total de vendas: {{ venda_total_formatada }}</h2>
    <h2>Quantidade de vendas: {{ quantidade_vendida }}</h2>

</body>
</html>